# Generated by Django 5.1.1 on 2024-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Введите цену продукта",
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
