# Generated by Django 5.1.1 on 2024-11-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Укажите, опубликован ли продукт",
                verbose_name="Статус публикации",
            ),
        ),
    ]
