# Generated by Django 5.1.1 on 2024-11-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "description", "category"],
                "permissions": [
                    ("can_unpublish_product", "Can_unpublish_product"),
                    ("can_delete_product", "Can delete product"),
                    ("can_edit_product", "Can edit product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
